"""
empty message

Revision ID: f7ff4d5b7b48
Revises: eabd8d7407df
Create Date: 2025-03-05 13:40:00.333268

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7ff4d5b7b48'
down_revision: str | None = 'eabd8d7407df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


if not sqlmodel.sql:
    raise Exception('Something went wrong')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_cabinet')
    op.drop_table('schedule')
    op.drop_table('schedule_subject')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('student_class', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('student_class')

    op.create_table(
        'schedule_subject',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('schedule_id', sa.INTEGER(), nullable=False),
        sa.Column('subject_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['schedule_id'],
            ['schedule.id'],
        ),
        sa.ForeignKeyConstraint(
            ['subject_id'],
            ['subject.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'schedule',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('dateandtime', sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'schedule_cabinet',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('schedule_id', sa.INTEGER(), nullable=False),
        sa.Column('cabinet_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cabinet_id'],
            ['cabinet.id'],
        ),
        sa.ForeignKeyConstraint(
            ['schedule_id'],
            ['schedule.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    # ### end Alembic commands ###
