"""
empty message

Revision ID: 5ac50dcb9f4a
Revises: f9926303d830
Create Date: 2025-03-05 12:01:23.234546

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ac50dcb9f4a'
down_revision: str | None = 'f9926303d830'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


if not sqlmodel.sql:
    raise Exception('Something went wrong')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = sa.table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
        sa.Column('paternity', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
        sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
        sa.Column('birthdate', sa.DateTime(), nullable=True),
        sa.Column('login', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
        sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
    )

    op.bulk_insert(
        users_table,
        [
            {
                'id': 1,
                'surname': 'admin',
                'name': 'admin',
                'paternity': 'admin',
                'gender': 'admin',
                'birthdate': None,
                'login': 'admin',
                'password': 'admin',
                'role_id': 1,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
